export const PLAY_VIDEO = 'PLAY_VIDEO';
export const PAUSE_VIDEO = 'PAUSE_VIDEO';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const SET_VIDEO_PLAYED = 'SET_VIDEO_PLAYED';
export const SET_VIDEO_LOADED = 'SET_VIDEO_LOADED';
export const SET_VIDEO_DURATION = 'SET_VIDEO_DURATION';
export const SET_VIDEO_VOLUME = 'SET_VIDEO_VOLUME';
